export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_POSTS = 'FETCH_POSTS';
export const SET_USER_DRADTS = 'SET_USER_DRADTS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
